// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEgwjl2yqs9rFaYG6eYX8-AabZenilR6E',
    appId: '1:1032938815342:web:51675c9ec001808f7a8b7f',
    messagingSenderId: '1032938815342',
    projectId: 'trust-reservation-second',
    authDomain: 'trust-reservation-second.firebaseapp.com',
    storageBucket: 'trust-reservation-second.appspot.com',
    measurementId: 'G-3QTGHRPT8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0r_D9gTjzKQ33d4qIQZvNdfSKD_OysiY',
    appId: '1:1032938815342:android:6f1e30b93642c6817a8b7f',
    messagingSenderId: '1032938815342',
    projectId: 'trust-reservation-second',
    storageBucket: 'trust-reservation-second.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWbZGSo12eR3ATdV4iFunfvd5kr3pLDrk',
    appId: '1:1032938815342:ios:e3d0823cd462a95d7a8b7f',
    messagingSenderId: '1032938815342',
    projectId: 'trust-reservation-second',
    storageBucket: 'trust-reservation-second.appspot.com',
    iosBundleId: 'com.example.trustReservationSecond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWbZGSo12eR3ATdV4iFunfvd5kr3pLDrk',
    appId: '1:1032938815342:ios:e3d0823cd462a95d7a8b7f',
    messagingSenderId: '1032938815342',
    projectId: 'trust-reservation-second',
    storageBucket: 'trust-reservation-second.appspot.com',
    iosBundleId: 'com.example.trustReservationSecond',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEgwjl2yqs9rFaYG6eYX8-AabZenilR6E',
    appId: '1:1032938815342:web:a1a6febcc63ee62b7a8b7f',
    messagingSenderId: '1032938815342',
    projectId: 'trust-reservation-second',
    authDomain: 'trust-reservation-second.firebaseapp.com',
    storageBucket: 'trust-reservation-second.appspot.com',
    measurementId: 'G-J58DGJ1PFE',
  );
}
